#!/usr/bin/env python3
"""Generate fixed daily content from the Excel course master."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from zipfile import ZipFile

_shared_path = Path(__file__).resolve().parent / "generate-course-plan-catalog.py"
_shared_spec = importlib.util.spec_from_file_location("course_plan_generator", _shared_path)
if _shared_spec is None or _shared_spec.loader is None:
    raise RuntimeError(f"无法载入共享 Excel 解析器：{_shared_path}")
_shared = importlib.util.module_from_spec(_shared_spec)
_shared_spec.loader.exec_module(_shared)

CatalogError = _shared.CatalogError
PROJECT_ROOT = _shared.PROJECT_ROOT
read_sheet = _shared.read_sheet
shared_strings = _shared.shared_strings
sheet_targets = _shared.sheet_targets
table_records = _shared.table_records

DEFAULT_INPUT = PROJECT_ROOT.parent / "outputs" / "course-master-foundation-20260807" / "家庭长期课程总表.xlsx"
DEFAULT_JSON = PROJECT_ROOT / "curriculum" / "summer-plan-content.json"
DEFAULT_JS = PROJECT_ROOT / "curriculum" / "summer-plan-content.js"


def fail(message: str) -> None:
    raise CatalogError(f"暑假计划内容无效：{message}")


def text(record: dict, key: str, sheet: str) -> str:
    value = str(record.get(key, "") or "").strip()
    if not value:
        fail(f"工作表“{sheet}”第 {record.get('_row', '?')} 行的“{key}”不能为空")
    return value


def positive_integer(record: dict, key: str, sheet: str) -> int:
    value = record.get(key, "")
    try:
        number = int(value)
    except (TypeError, ValueError):
        fail(f"工作表“{sheet}”第 {record.get('_row', '?')} 行的“{key}”必须是正整数")
    if number <= 0 or str(value).strip() not in {str(number), f"{number}.0"}:
        fail(f"工作表“{sheet}”第 {record.get('_row', '?')} 行的“{key}”必须是正整数")
    return number


def tags(value: str) -> list[str]:
    result = [item.strip() for item in value.replace("，", ",").split(",") if item.strip()]
    if not result:
        fail("关键词至少需要一项")
    return result


def validate_days(days: list[dict], module_id: str) -> None:
    actual = [item["day"] for item in days]
    expected = list(range(1, 27))
    if actual != expected:
        fail(f"{module_id} 的 Day 必须恰好为 1–26，当前为 {actual}")


def normalize_poem(records: list[dict]) -> dict:
    days = []
    for record in records:
        day = positive_integer(record, "Day", "古诗计划")
        week = positive_integer(record, "周次", "古诗计划")
        study_type = text(record, "类型", "古诗计划")
        if study_type not in {"学习", "复习"}:
            fail(f"工作表“古诗计划”第 {record.get('_row', '?')} 行的类型必须是学习或复习")
        required = text(record, "必背", "古诗计划")
        optional = text(record, "选背", "古诗计划")
        days.append({
            "day": day,
            "title": text(record, "任务标题", "古诗计划"),
            "detail": f"必背：{required}\n选背：{optional}",
            "tags": tags(text(record, "关键词", "古诗计划")),
            "instruction": text(record, "孩子执行步骤", "古诗计划"),
            "minutes": positive_integer(record, "分钟", "古诗计划"),
            "metadata": {
                "week": week,
                "type": study_type,
                "required": required,
                "optional": optional,
                "source": text(record, "内容来源", "古诗计划"),
            },
        })
    days.sort(key=lambda item: item["day"])
    validate_days(days, "poem")
    return {"title": "古诗背诵", "days": days}


def load_records(path: Path) -> list[dict]:
    with ZipFile(path) as archive:
        strings = shared_strings(archive)
        targets = sheet_targets(archive)
        headers = ["Day", "周次", "类型", "必背", "选背", "关键词", "任务标题", "孩子执行步骤", "分钟", "内容来源"]
        if "古诗计划" not in targets:
            fail("缺少工作表“古诗计划”")
        return table_records(read_sheet(archive, targets["古诗计划"], strings), headers, "古诗计划")


def render_json(value: dict) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def render_js(value: dict) -> str:
    body = json.dumps(value, ensure_ascii=False, indent=2).replace("\n", "\n  ")
    return (
        "(function (root) {\n"
        "  // Generated by scripts/generate-summer-plan-content.py. Do not edit directly.\n"
        f"  root.SUMMER_PLAN_CONTENT = Object.freeze({body});\n"
        "})(typeof window === \"undefined\" ? globalThis : window);\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--js-output", type=Path, default=DEFAULT_JS)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        poem_records = load_records(args.input)
        source = {
            "type": "xlsx",
            "file": str(Path("..") / args.input.relative_to(PROJECT_ROOT.parent)),
            "sha256": hashlib.sha256(args.input.read_bytes()).hexdigest(),
        }
        value = {
            "schemaVersion": 1,
            "source": source,
            "modules": {
                "poem": normalize_poem(poem_records),
            },
        }
        outputs = [(args.json_output, render_json(value)), (args.js_output, render_js(value))]
        if args.check:
            stale = [path for path, generated in outputs if not path.exists() or path.read_text(encoding="utf-8") != generated]
            if stale:
                print("暑假计划内容生成结果已过期。请运行：python3 scripts/generate-summer-plan-content.py", file=sys.stderr)
                return 1
            print("OK: 暑假计划固定内容已校验（古诗 26 天；数学为家长每日填写）")
            return 0
        for path, generated in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(generated, encoding="utf-8")
        print("已生成 curriculum/summer-plan-content.json 与 curriculum/summer-plan-content.js（古诗 26 天；数学为家长每日填写）")
        return 0
    except (CatalogError, KeyError, OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
